<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.ZAIN.com/ZESB/BusinessSchemas/GetPrepaidBalForPostpaidRes.xsd" xmlns:ns="http://www.ZAIN.com/ZESB/BusinessSchemas/GetPrepaidBalForPostpaidReq.xsd" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://www.zain.com/ZESB/Services/GetPrepaidBalForPostpaid" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zain.com/ZESB/Services/GetPrepaidBalForPostpaid">
    <import namespace="http://www.ZAIN.com/ZESB/BusinessSchemas/GetPrepaidBalForPostpaidReq.xsd" location="../../../../BusinessSchemas/Services/Query/GetPrepaidBalForPostpaid/GetPrepaidBalForPostpaidReq.xsd"/>
    <import namespace="http://www.ZAIN.com/ZESB/BusinessSchemas/GetPrepaidBalForPostpaidRes.xsd" location="../../../../BusinessSchemas/Services/Query/GetPrepaidBalForPostpaid/GetPrepaidBalForPostpaidRes.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../../CDM/ZainKWFault.xsd"/>
    <message name="GetPrepaidBalForPostpaidReq">
        <part name="Req" element="ns:GetPrepaidBalForPostpaidReq"/>
    </message>
    <message name="GetPrepaidBalForPostpaidRes">
        <part name="Res" element="ns2:GetPrepaidBalForPostpaidRes"/>
    </message>
    <message name="GetPrepaidBalForPostpaidFault">
        <part name="Fault" element="ns3:ErrorResponse"/>
    </message>
    <portType name="GetPrepaidBalForPostpaidPortType">
        <operation name="GetPrepaidBalForPostpaidOp">
            <input message="tns:GetPrepaidBalForPostpaidReq"/>
            <output message="tns:GetPrepaidBalForPostpaidRes"/>
            <fault name="fault1" message="tns:GetPrepaidBalForPostpaidFault"/>
        </operation>
    </portType>
</definitions>