<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.zain.com/ZESB/Services/TosaCPInbound/TosaCPFault" xmlns:tns="http://xmlns.example.com/1650994429612" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="http://www.zain.com/ZESB/Services/TosaCPInbound/TosaCPCRMManagePNRes" xmlns:ns3="http://www.zain.com/ZESB/Services/TosaCPInbound/TosaCPCRMManagePNReq" targetNamespace="http://xmlns.example.com/1650994429612">
    <documentation>Manage Preferred Number from CRM</documentation>
    <import namespace="http://www.zain.com/ZESB/Services/TosaCPInbound/TosaCPFault" location="../../../../BusinessSchemas/Services/Applications/ExternalChannel/TosaCPInbound/Fault.xsd"/>
    <import namespace="http://www.zain.com/ZESB/Services/TosaCPInbound/TosaCPCRMManagePNRes" location="../../../../BusinessSchemas/Services/Applications/ExternalChannel/TosaCPInbound/TosaCPCRMManagePNRes.xsd"/>
    <import namespace="http://www.zain.com/ZESB/Services/TosaCPInbound/TosaCPCRMManagePNReq" location="../../../../BusinessSchemas/Services/Applications/ExternalChannel/TosaCPInbound/TosaCPCRMManagePNReq.xsd"/>
    <message name="TosaCPCRMManagePNReq">
        <part name="TosaCPCRMManagePNReq" element="ns3:TosaCPCRMManagePNReq"/>
    </message>
    <message name="TosaCPCRMManagePNRes">
        <part name="TosaCPCRMManagePNRes" element="ns2:TosaCPAddPNRes"/>
    </message>
    <message name="Fault">
        <part name="fault" element="ns:Fault"/>
    </message>
    <portType name="TosaCPCRMManagePNPortType">
        <operation name="TosaCPCRMManagePNOp">
            <input message="tns:TosaCPCRMManagePNReq"/>
            <output message="tns:TosaCPCRMManagePNRes"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>