<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/OSS_BSS_BW_CATALOG/BusinessProcesses/CatalogSync/Resources/Schema/Schema.xsd" xmlns:tns="http://www.ericsson.com/obslab/interface/TIBCOCatalogSync" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.ericsson.com/obslab/interface/TIBCOCatalogSync">
    <import namespace="http://www.tibco.com/schemas/OSS_BSS_BW_CATALOG/BusinessProcesses/CatalogSync/Resources/Schema/Schema.xsd" location="../Schema/CatalagSync.xsd"/>
    <message name="TIBCOCatalogSyncRequst">
        <part name="Input" element="ns:exportCatalogRequest"/>
    </message>
    <message name="TIBCOCatalogSyncResponse">
        <part name="Output" element="ns:catalogSyncResponse"/>
    </message>
    <portType name="TIBCOCatalogSyncPortType">
        <operation name="TIBCOCatalogSyncOperation">
            <input message="tns:TIBCOCatalogSyncRequst"/>
            <output message="tns:TIBCOCatalogSyncResponse"/>
        </operation>
    </portType>
</definitions>