<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/BusinessSchemas/Services/Common/JMSSchema/JMSHeader.xsd" xmlns:tns="http://xmlns.example.com/1448612185004" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1448612185004">
    <import location="JMSHeader.xsd" namespace="http://www.ericsson.com/BusinessSchemas/Services/Common/JMSSchema/JMSHeader.xsd"/>
    <message name="Message">
        <part element="ns:_applicationProperties" name="JMSHeader"/>
    </message>
</definitions>