<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.zain.com/BusinessSchemas/Services/TerminateMsisdnUpdate" xmlns:tns="http://xmlns.example.com/1628576648697" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1628576648697">
    <import namespace="http://www.zain.com/BusinessSchemas/Services/TerminateMsisdnUpdate" location="../../../../BusinessSchemas/Services/Applications/CRM/Update/TerminateMsisdnUpdate.xsd"/>
    <message name="TerminateMsisdnUpdateReq">
        <part name="Request" element="ns:TerminateMsisdnUpdateRequest"/>
    </message>
    <message name="TerminateMsisdnUpdateRes">
        <part name="Response" element="ns:TerminateMsisdnUpdateResponse"/>
    </message>
    <portType name="TerminateMsisdnUpdatePort">
        <operation name="TerminateMsisdnUpdateOp">
            <input message="tns:TerminateMsisdnUpdateReq"/>
            <output message="tns:TerminateMsisdnUpdateRes"/>
        </operation>
    </portType>
</definitions>