<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:ns="http://www.siebel.com/xml/External/InteractionHistory" xmlns:tns="http://www.zain.com/ZESB/Services/InteractionHistory" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zain.com/ZESB/Services/InteractionHistory">
    <import namespace="http://www.siebel.com/xml/External/InteractionHistory" location="../../../BusinessSchemas/Services/Applications/ExternalChannel/InteractionHistory/InteractionHistory.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <message name="InteractionHistoryReq">
        <part name="InteractionHistoryReq" element="ns:IntercationHistoryService"/>
    </message>
    <message name="InteractionHistoryRes">
        <part name="InteractionHistoryRes" element="ns:IntercationHistoryService"/>
    </message>
    <message name="fault">
        <part name="fault" element="ns2:ErrorResponse"/>
    </message>
    <portType name="InteractioHistotyPort">
        <operation name="InteractionHistory">
            <input message="tns:InteractionHistoryReq"/>
            <output message="tns:InteractionHistoryRes"/>
            <fault name="fault1" message="tns:fault"/>
        </operation>
    </portType>
</definitions>