<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.tibco.com/schemas/Recaching/Resources/Schema.xsd2" xmlns:ns="http://www.tibco.com/schemas/Recaching/Resources/Schema.xsd" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.example.com/1482784290093" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1482784290093">
    <import location="RecachingReq.xsd" namespace="http://www.tibco.com/schemas/Recaching/Resources/Schema.xsd"/>
    <import location="RecachingRes.xsd" namespace="http://www.tibco.com/schemas/Recaching/Resources/Schema.xsd2"/>
    <import location="../CDM/ZainKWFault.xsd" namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd"/>
    <message name="Fault">
        <part element="ns3:ErrorResponse" name="part1"/>
    </message>
    <message name="Response">
        <part element="ns2:RecachingRes" name="part1"/>
    </message>
    <message name="Request">
        <part name="part1" element="ns:RecachingRequest"/>
    </message>
    <portType name="RecachingPort">
        <operation name="Recaching">
            <input message="tns:Request"/>
            <output message="tns:Response"/>
            <fault message="tns:Fault" name="fault1"/>
        </operation>
    </portType>
</definitions>