<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/AverageInvoiceDetailsReq" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/AverageInvoiceDetailsRes" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.example.com/1614674969322" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1614674969322">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/AverageInvoiceDetailsRes" location="../../../BusinessSchemas/Services/Query/AverageInvoiceDetails/AverageInvoiceDetailsRes.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/AverageInvoiceDetailsReq" location="../../../BusinessSchemas/Services/Query/AverageInvoiceDetails/AverageInvoiceDetailsReq.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <message name="AverageInvoiceDetailsIn">
        <part name="Request" element="ns2:AverageInvoiceDetailsReq"/>
    </message>
    <message name="AverageInvoiceDetailsOp">
        <part name="Response" element="ns:AverageInvoiceDetailsRes"/>
    </message>
    <message name="Fault">
        <part name="Fault" element="ns3:ErrorResponse"/>
    </message>
    <portType name="AverageInvoiceDetailsPortType">
        <operation name="AverageInvoiceDetails">
            <input message="tns:AverageInvoiceDetailsIn"/>
            <output message="tns:AverageInvoiceDetailsOp"/>
            <fault name="fault" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>