<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/GW_OrdMgmt/Schemas/CancelFutureDatedOrderSchema.xsd" xmlns:tns="http://xmlns.Zain.com/BSS/ESB/OrderMgmt/cancelFutureOrder" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.Zain.com/BSS/ESB/OrderMgmt/cancelFutureOrder">
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <import namespace="http://www.tibco.com/schemas/GW_OrdMgmt/Schemas/CancelFutureDatedOrderSchema.xsd" location="../../../BusinessSchemas/Services/Applications/ExternalChannel/cancelFutureOrder/CancelFutureOrder.xsd"/>
    <message name="cancelFutureOrderRequest">
        <part name="cancelFutureOrderReq" element="ns:cancelFutureorderRequest"/>
    </message>
    <message name="cancelFutureOrderResponse">
        <part name="cancelFutureOrderRes" element="ns:cancelFutureOrderResponse"/>
    </message>
    <message name="fault">
        <part name="fault" element="ns2:ErrorResponse"/>
    </message>
    <portType name="PortType">
        <operation name="cancelFutureOrder">
            <input message="tns:cancelFutureOrderRequest"/>
            <output message="tns:cancelFutureOrderResponse"/>
            <fault message="tns:fault"/>
        </operation>
    </portType>
</definitions>