<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/ContractStatusUpdate.xsd" xmlns:tns="http://xmlns.zain.com/BSS/ESB/ContractStatusUpdate" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.zain.com/BSS/ESB/ContractStatusUpdate">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/ContractStatusUpdate.xsd" location="../../../BusinessSchemas/Services/Applications/Common/ContractStatusUpdate/ContractStatusUpdate.xsd"/>
    <message name="ContractStatusUpdateReq">
        <part name="ContractStatusUpdateIp" element="ns:ContractStatusUpdateReq"/>
    </message>
    <message name="ContractStatusUpdateRes">
        <part name="ContractStatusUpdateOp" element="ns:ContractStatusUpdateRes"/>
    </message>
    <message name="FaultMessage">
        <part name="Fault" element="ns:Fault"/>
    </message>
    <portType name="ContractStatusUpdatePortType">
        <operation name="ContractStatusUpdate">
            <input message="tns:ContractStatusUpdateReq"/>
            <output message="tns:ContractStatusUpdateRes"/>
            <fault name="fault1" message="tns:FaultMessage"/>
        </operation>
    </portType>
</definitions>