<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/ContractRead.xsd" xmlns:tns="http://xmlns.example.com/1488734105166" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1488734105166">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/ContractRead.xsd" location="../../../BusinessSchemas/Services/Query/ContractRead/ContractRead.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <message name="ContractReadInput">
        <part name="Input" element="ns:ContractReadRequest"/>
    </message>
    <message name="ContractReadOutput">
        <part name="Output" element="ns:ContractReadResponse"/>
    </message>
    <message name="ContractReadFault">
        <part name="Fault" element="ns2:ErrorResponse"/>
    </message>
    <portType name="ContractReadPort">
        <operation name="ContractRead">
            <input message="tns:ContractReadInput"/>
            <output message="tns:ContractReadOutput"/>
            <fault name="fault1" message="tns:ContractReadFault"/>
        </operation>
    </portType>
</definitions>