<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/CorpCustomerBalance.xsd" xmlns:tns="http://xmlns.example.com/1499241210726" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1499241210726">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/CorpCustomerBalance.xsd" location="../../../BusinessSchemas/Services/Query/CorpCustomerBalance/CorpCustomerBalance.xsd"/>
    <message name="CorpCustomerBalanceInput">
        <part name="Input" element="ns:CorpCustomerBalanceRequest"/>
    </message>
    <message name="CorpCustomerBalanceOutput">
        <part name="Output" element="ns:CorpCustomerBalanceResponse"/>
    </message>
    <portType name="CorpCustomerBalancePort">
        <operation name="CorpCustomerBalance">
            <input message="tns:CorpCustomerBalanceInput"/>
            <output message="tns:CorpCustomerBalanceOutput"/>
        </operation>
    </portType>
</definitions>