<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/CreditProfileHistReadService.xsd" xmlns:tns="http://xmlns.example.com/1463655061081" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1463655061081">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/CreditProfileHistReadService.xsd" location="../../../BusinessSchemas/Services/Query/CreditProfileHistRead/CreditProfileHistRead.xsd"/>
    <message name="CreditProfileHistReadRequest">
        <part name="Input" element="ns:CreditProfileHistReadRequest"/>
    </message>
    <message name="CreditProfileHistReadResponse">
        <part name="Output" element="ns:CreditProfileHistReadResponse"/>
    </message>
    <message name="CreditProfileHistReadFault">
        <part name="fault" element="ns:Fault"/>
    </message>
    <portType name="CreditProfileHistReadPort">
        <operation name="CreditProfileHistReadOperation">
            <input message="tns:CreditProfileHistReadRequest"/>
            <output message="tns:CreditProfileHistReadResponse"/>
            <fault name="fault1" message="tns:CreditProfileHistReadFault"/>
        </operation>
    </portType>
</definitions>