<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/CreditActionsRead/Schema.xsd" xmlns:tns="http://xmlns.example.com/1463654594825" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1463654594825">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/CreditActionsRead/Schema.xsd" location="../../../BusinessSchemas/Services/Query/CreditActionsRead/CreditActionsRead.xsd"/>
    <message name="CreditActionsReadRequest">
        <part name="Input" element="ns:CreditActionsReadRequest"/>
    </message>
    <message name="CreditActionsReadResponse">
        <part name="Output" element="ns:CreditActionsReadResponse"/>
    </message>
    <message name="CreditActionsReadFault">
        <part name="fault" element="ns:Fault"/>
    </message>
    <portType name="CreditActionsReadPort">
        <operation name="CreditActionsReadOperation">
            <input message="tns:CreditActionsReadRequest"/>
            <output message="tns:CreditActionsReadResponse"/>
            <fault name="fault1" message="tns:CreditActionsReadFault"/>
        </operation>
    </portType>
</definitions>