<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/CustomerDunning.xsd" xmlns:tns="http://xmlns.zain.com/BSS/ESB/CustomerDunning" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.zain.com/BSS/ESB/CustomerDunning">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/CustomerDunning.xsd" location="../../../BusinessSchemas/Services/Applications/Common/Dunning/CustomerDunning.xsd"/>
    <message name="CustomerDunningInput">
        <part name="CustomerDunningIp" element="ns:CustomerDunningInput"/>
    </message>
    <message name="CustomerDunningOutput">
        <part name="CustomerDunningOp" element="ns:CustomerDunningOutput"/>
    </message>
    <message name="Fault">
        <part name="FaultMessage" element="ns:Fault"/>
    </message>
    <portType name="CustomerDunningPortType">
        <operation name="CustomerDunningAction">
            <input message="tns:CustomerDunningInput"/>
            <output message="tns:CustomerDunningOutput"/>
            <fault name="fault" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>