<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/CustomerRiskRead.xsd" xmlns:tns="http://xmlns.example.com/1494840129551" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1494840129551">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/CustomerRiskRead.xsd" location="../../../BusinessSchemas/Services/Query/CustomerRiskRead/CustomerRiskRead.xsd"/>
    <message name="CustomerRiskReadInput">
        <part name="Input" element="ns:CustomerRiskReadRequest"/>
    </message>
    <message name="CustomerRiskReadOutput">
        <part name="Output" element="ns:CustomerRiskReadResponse"/>
    </message>
    <portType name="CustomerRiskReadPort">
        <operation name="CustomerRiskRead">
            <input message="tns:CustomerRiskReadInput"/>
            <output message="tns:CustomerRiskReadOutput"/>
        </operation>
    </portType>
</definitions>