<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.ericsson.com/ZainKW/CommonProject/BusinessSchemas/Services/Modification/CustCatBasedDiscountUpdateResponse.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/CommonProject/BusinessSchemas/Services/Modification/CustCatBasedDiscountUpdateRequest.xsd" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.zain.com/BSS/ESB/Financial/CustCatBasedDiscountUpdate" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.zain.com/BSS/ESB/Financial/CustCatBasedDiscountUpdate">
    <import namespace="http://www.ericsson.com/ZainKW/CommonProject/BusinessSchemas/Services/Modification/CustCatBasedDiscountUpdateRequest.xsd" location="../../../BusinessSchemas/Services/Modification/CustCatBasedDiscountUpdate/CustCatBasedDiscountRequest.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/CommonProject/BusinessSchemas/Services/Modification/CustCatBasedDiscountUpdateResponse.xsd" location="../../../BusinessSchemas/Services/Modification/CustCatBasedDiscountUpdate/CustCatBasedDiscountResponse.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <message name="CustCatDiscountUpdateInput">
        <part name="input" element="ns:CustCatBasedDiscountReq"/>
    </message>
    <message name="CustCatDiscountUpdateOutput">
        <part name="output" element="ns2:CustCatBasedDiscountResponse"/>
    </message>
    <message name="CustCatDiscountUpdateFault">
        <part name="fault" element="ns3:ErrorResponse"/>
    </message>
    <portType name="CustCatDiscountUpdatePortType">
        <operation name="CustCatDiscountUpdateOperation">
            <input message="tns:CustCatDiscountUpdateInput"/>
            <output message="tns:CustCatDiscountUpdateOutput"/>
            <fault name="fault1" message="tns:CustCatDiscountUpdateFault"/>
        </operation>
    </portType>
</definitions>