<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.ericsson.com/BusinessSchemas/Modification/CustomerCategoryChange/CustCatChangeCEERes.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/BusinessSchemas/Modification/CustomerCategoryChange/CustCatChangeCEEReq.xsd" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.zain.com/BSS/ESB/Modification/CustCategoryChangeCEE" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.zain.com/BSS/ESB/Modification/CustCategoryChangeCEE">
    <documentation>CRM-&gt;ESB-&gt;EOM</documentation>
    <import namespace="http://www.ericsson.com/BusinessSchemas/Modification/CustomerCategoryChange/CustCatChangeCEEReq.xsd" location="../../../BusinessSchemas/Services/Modification/CustomerCategoryChange/CustCatChangeCEEReq.xsd"/>
    <import namespace="http://www.ericsson.com/BusinessSchemas/Modification/CustomerCategoryChange/CustCatChangeCEERes.xsd" location="../../../BusinessSchemas/Services/Modification/CustomerCategoryChange/CustCatChangeCEERes.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <message name="CustCategoryChangeCEEReq">
        <part name="Req" element="ns:CustCatChangeCEEReq"/>
    </message>
    <message name="CustCategoryChangeCEERes">
        <part name="Res" element="ns2:CustCatChangeCEERes"/>
    </message>
    <message name="Fault">
        <part name="fault" element="ns3:ErrorResponse"/>
    </message>
    <portType name="CustCategoryChangeCEEPortType">
        <operation name="CustCategoryChangeCEEOp">
            <input message="tns:CustCategoryChangeCEEReq"/>
            <output message="tns:CustCategoryChangeCEERes"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>