<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/Dunning.xsd" xmlns:tns="http://xmlns.zain.com/BSS/ESB/Dunning" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.zain.com/BSS/ESB/Dunning">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/Dunning.xsd" location="../../../BusinessSchemas/Services/Applications/Common/Dunning/Dunning.xsd"/>
    <message name="DunningInput">
        <part name="DunningInput" element="ns:OrderRequest"/>
    </message>
    <message name="DunningOutput">
        <part name="DunningOutput" element="ns:OrderResponse"/>
    </message>
    <message name="FaultMessage">
        <part name="FaultElement" element="ns:Fault"/>
    </message>
    <portType name="DunningPortType">
        <operation name="Order">
            <input message="tns:DunningInput"/>
            <output message="tns:DunningOutput"/>
            <fault name="fault" message="tns:FaultMessage"/>
        </operation>
    </portType>
</definitions>