<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/FirstCallUpdateService.xsd" xmlns:tns="http://xmlns.example.com/1529488939439" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1529488939439">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/FirstCallUpdateService.xsd" location="../../../BusinessSchemas/Services/Modification/FirstCallUpdateService/FirstCallUpdateService.xsd"/>
    <message name="FirstCallUpdateInput">
        <part name="Input" element="ns:FirstCallUpdateRequest"/>
    </message>
    <message name="FirstCallUpdateOutput">
        <part name="Output" element="ns:FirstCallUpdateResponse"/>
    </message>
    <portType name="FirstCallUpdatePort">
        <operation name="FirstCallUpdate">
            <input message="tns:FirstCallUpdateInput"/>
            <output message="tns:FirstCallUpdateOutput"/>
        </operation>
    </portType>
</definitions>