<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.zain.com/ZESB/Services/GenerateESIMRes" xmlns:ns="http://www.zain.com/ZESB/Services/GenerateESIMReq" xmlns:ns3="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" xmlns:tns="http://www.zain.com/ZESB/Services/GenerateESIMService" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zain.com/ZESB/Services/GenerateESIMService">
    <import location="../../../BusinessSchemas/Services/Applications/ExternalChannel/GenerateESIMQRCode/GenerateESIMReq.xsd" namespace="http://www.zain.com/ZESB/Services/GenerateESIMReq"/>
    <import location="../../../BusinessSchemas/Services/Applications/ExternalChannel/GenerateESIMQRCode/GenerateESIMRes.xsd" namespace="http://www.zain.com/ZESB/Services/GenerateESIMRes"/>
    <import location="../../../BusinessSchemas/Services/Common/SOAP/Fault.xsd" namespace="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd"/>
    <message name="GenerateESIMServicesReq">
        <part element="ns:GenerateESIMReq" name="request"/>
    </message>
    <message name="GenerateESIMServicesRes">
        <part name="response" element="ns2:GenerateESIMRes"/>
    </message>
    <message name="faultMessage">
        <part element="ns3:ExceptionRequest" name="fault"/>
    </message>
    <portType name="GenerateESIMServicePort">
        <operation name="GenerateESIMService">
            <input message="tns:GenerateESIMServicesReq"/>
            <output message="tns:GenerateESIMServicesRes"/>
            <fault message="tns:faultMessage" name="fault"/>
        </operation>
    </portType>
</definitions>