<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/CRM/Query/GetOfferExpiry/Schema.xsd" xmlns:ns4="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/CRM/Query/GetOfferExpiryResponse.xsd" xmlns:ns3="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/CRM/Query/GetOfferExpiryRequest.xsd" xmlns:tns="http://xmlns.example.com/1603971982690" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1603971982690">
    <import namespace="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" location="../../../BusinessSchemas/Services/Common/SOAP/Fault.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/CRM/Query/GetOfferExpiryRequest.xsd" location="../../../BusinessSchemas/Services/Applications/CRM/Query/GetOfferExpiry/GetOfferExpiryRequest.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/CRM/Query/GetOfferExpiryResponse.xsd" location="../../../BusinessSchemas/Services/Applications/CRM/Query/GetOfferExpiry/GetOfferExpiryResponse.xsd"/>
    <message name="GetOfferExpiryInput">
        <part name="GetOfferExpiryInput" element="ns3:GetOfferExpiryReq"/>
    </message>
    <message name="GetOfferExpiryOutput">
        <part name="GetOfferExpiryOutput" element="ns4:GetOfferExpiryRes"/>
    </message>
    <portType name="GetOfferExpiryPortType">
        <operation name="GetOfferExpiry">
            <input message="tns:GetOfferExpiryInput"/>
            <output message="tns:GetOfferExpiryOutput"/>
        </operation>
    </portType>
</definitions>