<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/CRM/BillProcessCreate.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Applications/CRM/Update/Schema.xsd" xmlns:tns="http://xmlns.example.com/1455610176556" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1455610176556">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/CRM/BillProcessCreate.xsd" location="../../../BusinessSchemas/Services/Applications/CRM/Update/BillProcessCreate.xsd"/>
    <message name="BillProcessCreateInput">
        <part name="BillProcessCreateInput" element="ns2:BillProcessCreateRequest"/>
    </message>
    <message name="BillProcessCreateOutput">
        <part name="BillProcessCreateOutput" element="ns2:BillProcessCreateResponse"/>
    </message>
    <message name="FaultMessage">
        <part name="faultElement" element="ns2:Fault"/>
    </message>
    <portType name="BillProcessCreatePortType">
        <operation name="BillProcessCreate">
            <input message="tns:BillProcessCreateInput"/>
            <output message="tns:BillProcessCreateOutput"/>
            <fault name="fault1" message="tns:FaultMessage"/>
        </operation>
    </portType>
</definitions>