<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/InstallmentPeriodUpdReq" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/InstallmentPeriodUpdRes" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.example.com/1614674969322" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1614674969322">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/InstallmentPeriodUpdRes" location="../../../BusinessSchemas/Services/Modification/InstallmentPeriodUpdate/InstallmentPeriodUpdRes.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/InstallmentPeriodUpdReq" location="../../../BusinessSchemas/Services/Modification/InstallmentPeriodUpdate/InstallmentPeriodUpdReq.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <message name="InstallmentPeriodUpdIn">
        <part name="Request" element="ns2:InstallmentPeriodUpdReq"/>
    </message>
    <message name="InstallmentPeriodUpdOp">
        <part name="Response" element="ns:InstallmentPeriodUpdRes"/>
    </message>
    <message name="Fault">
        <part name="Fault" element="ns3:ErrorResponse"/>
    </message>
    <portType name="InstallmentPeriodUpdPortType">
        <operation name="InstallmentPeriodUpd">
            <input message="tns:InstallmentPeriodUpdIn"/>
            <output message="tns:InstallmentPeriodUpdOp"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>