<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Query/InteractionHistory/InteractionHistoryOutput.xsd" xmlns:ns="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Query/InteractionHistory/InteractionHistoryInput.xsd" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.example.com/1458800909906" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1458800909906">
    <import namespace="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Query/InteractionHistory/InteractionHistoryInput.xsd" location="../../../BusinessSchemas/Services/Query/InteractionHistory/InteractionHistoryInput.xsd"/>
    <import namespace="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Query/InteractionHistory/InteractionHistoryOutput.xsd" location="../../../BusinessSchemas/Services/Query/InteractionHistory/InteractionHistoryOutput.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <message name="InteractionHistoryRequest">
        <part name="part1" element="ns:InteractionHistoryRequest"/>
    </message>
    <message name="InteractionHistoryResponse">
        <part name="part1" element="ns2:InteractionHistoryOutput"/>
    </message>
    <message name="Fault">
        <part name="part1" element="ns3:ErrorResponse"/>
    </message>
    <portType name="InteractionHistoryPort">
        <operation name="InteractionHistory">
            <input message="tns:InteractionHistoryRequest"/>
            <output message="tns:InteractionHistoryResponse"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>