<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/InvoiceSummaryCRM.xsd" xmlns:tns="http://xmlns.zain.com/BSS/ESB/Financial/Query/InvoiceSummaryCRM" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.zain.com/BSS/ESB/Financial/Query/InvoiceSummaryCRM">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/InvoiceSummaryCRM.xsd" location="../../../BusinessSchemas/Services/Query/InvoiceSummaryCRM/InvoiceSummaryCRM.xsd"/>
    <message name="InvoiceSummaryCRMIn">
        <part name="Req" element="ns:InvoiceSummaryCRMRequest"/>
    </message>
    <message name="InvoiceSummaryCRMOp">
        <part name="Res" element="ns:InvoiceSummaryCRMResponse"/>
    </message>
    <portType name="InvoiceSummaryCRMPortType">
        <operation name="InvoiceSummaryCRMOperation">
            <input message="tns:InvoiceSummaryCRMIn"/>
            <output message="tns:InvoiceSummaryCRMOp"/>
        </operation>
    </portType>
</definitions>