<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/CreditControl/Customer/PaymentProfile" xmlns:tns="http://xmlns.zain.com/BSS/ESB/Customer/PaymentMethod" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.zain.com/BSS/ESB/Customer/PaymentMethod">
    <documentation>Service to handle updation of payment profile</documentation>
    <import location="../../../BusinessSchemas/Services/Applications/Common/ManagePaymentMethod/PaymentMethod.xsd" namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/CreditControl/Customer/PaymentProfile"/>
    <message name="PaymentMethodChangeReq">
        <part element="ns:PaymentMethodChangeReq" name="PaymentMethodChangeReq"/>
    </message>
    <message name="PaymentMethodChangeRes">
        <part element="ns:PaymentMethodChangeRes" name="PaymentMethodChangeRes"/>
    </message>
    <portType name="PaymentMethodPortType">
        <operation name="UpdatePaymentProfile">
            <input message="tns:PaymentMethodChangeReq"/>
            <output message="tns:PaymentMethodChangeRes"/>
        </operation>
    </portType>
</definitions>