<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/MsisdnPortStatusChange.xsd" xmlns:tns="http://xmlns.example.com/1528959034676" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1528959034676">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/MsisdnPortStatusChange.xsd" location="../../../BusinessSchemas/Services/Modification/MsisdnPortStatusChange/MsisdnPortStatusChange.xsd"/>
    <message name="MsisdnPortStatusChangeInput">
        <part name="Input" element="ns:MsisdnPortStatusChangeRequest"/>
    </message>
    <message name="MsisdnPortStatusChangeOutput">
        <part name="Output" element="ns:MsisdnPortStatusChangeResponse"/>
    </message>
    <portType name="MsisdnPortStatusChangePort">
        <operation name="MsisdnPortStatusChange">
            <input message="tns:MsisdnPortStatusChangeInput"/>
            <output message="tns:MsisdnPortStatusChangeOutput"/>
        </operation>
    </portType>
</definitions>