<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Transaction/MultiSubscriberPayment.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.zain.com/BSS/ESB/Financial/MultiSubscriberPayment" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.zain.com/BSS/ESB/Financial/MultiSubscriberPayment">
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Transaction/MultiSubscriberPayment.xsd" location="../../../BusinessSchemas/Services/Transaction/Payments/MultiSubscriberPayment.xsd"/>
    <message name="MultiSubscriberPaymentFault">
        <part name="fault" element="ns:ErrorResponse"/>
    </message>
    <message name="MultiSubscriberPaymentInput">
        <part name="Input" element="ns2:MultiSubsPaymentReq"/>
    </message>
    <message name="MultiSubscriberPaymentOutput">
        <part name="Output" element="ns2:MultiSubsPaymentRes"/>
    </message>
    <portType name="MultiSubscriberPaymentPortType">
        <operation name="MultiSubscriberPayment">
            <input message="tns:MultiSubscriberPaymentInput"/>
            <output message="tns:MultiSubscriberPaymentOutput"/>
            <fault name="fault1" message="tns:MultiSubscriberPaymentFault"/>
        </operation>
    </portType>
</definitions>