<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/ConceptWave/PaymentTransaction.xsd" xmlns:tns="http://xmlns.zain.com/BSS/ESB/Financial/OCCCharges" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.zain.com/BSS/ESB/Financial/OCCCharges">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/ConceptWave/PaymentTransaction.xsd" location="../../../BusinessSchemas/Services/Applications/ConceptWave/PaymentTransaction/PaymentTransaction.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <message name="OCCChargesFault">
        <part name="fault" element="ns2:ErrorResponse"/>
    </message>
    <message name="OCCChargesRequest">
        <part name="Input" element="ns:ChargeRequest"/>
    </message>
    <message name="OCCChargeResponse">
        <part name="Output" element="ns:ChargeResponse"/>
    </message>
    <portType name="OCCChargesPortType">
        <operation name="OCCChargeOperation">
            <input message="tns:OCCChargesRequest"/>
            <output message="tns:OCCChargeResponse"/>
            <fault name="fault1" message="tns:OCCChargesFault"/>
        </operation>
    </portType>
</definitions>