<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.tibco.com/schemas/GW_OrdMgmt/BusinessProcesses/Services/Common/OrderValidation/Implementation/OrderValidationOutput.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns4="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/OrderValidationInput.xsd" xmlns:ns="http://www.tibco.com/schemas/GW_OrdMgmt/BusinessProcesses/Services/Common/OrderValidation/Implementation/OrderValidationInput.xsd" xmlns:ns3="http://www.zain.com/ZESB/Types/Common" xmlns:tns="http://xmlns.example.com/1461137882558" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns5="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/OrderValidationOutput.xsd" xmlns:ns6="http://www.zain.com/ZESB/Services/SubscriberOrder" xmlns:ns7="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" targetNamespace="http://xmlns.example.com/1461137882558">
    <import location="../../../BusinessSchemas/Services/Applications/Common/OrderValidation/OrderValidationInput.xsd" namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/OrderValidationInput.xsd"/>
    <import location="../../../BusinessSchemas/Services/Applications/Common/OrderValidation/OrderValidationOutput.xsd" namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/OrderValidationOutput.xsd"/>
    <import location="../../../BusinessSchemas/Services/Common/SOAP/Fault.xsd" namespace="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd"/>
    <message name="OrderValidationInput">
        <part element="ns4:OrderValidationRequest" name="Input"/>
    </message>
    <message name="OrderValidationOutput">
        <part element="ns5:OrderValidationResponse" name="Output"/>
    </message>
    <message name="Fault">
        <part element="ns7:ExceptionRequest" name="FaultMessage"/>
    </message>
    <portType name="OrderValidationPortType">
        <operation name="OrderValidation">
            <input message="tns:OrderValidationInput"/>
            <output message="tns:OrderValidationOutput"/>
        </operation>
    </portType>
</definitions>