<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/OrderInstallationDetailsQuery.xsd" xmlns:tns="http://xmlns.example.com/1546499151168" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1546499151168">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/OrderInstallationDetailsQuery.xsd" location="../../../BusinessSchemas/Services/Query/OrderInstallationDetailsQuery/OrderInstallationDetailsQuery.xsd"/>
    <message name="OrderInstallationDetailsQueryRequest">
        <part name="Input" element="ns:OrderInstallationDetailsQueryInput"/>
    </message>
    <message name="OrderInstallationDetailsQueryResponse">
        <part name="Output" element="ns:OrderInstallationDetailsQueryOutput"/>
    </message>
    <portType name="OrderInstallationDetailsQueryPort">
        <operation name="OrderInstallationDetailsQuery">
            <input message="tns:OrderInstallationDetailsQueryRequest"/>
            <output message="tns:OrderInstallationDetailsQueryResponse"/>
        </operation>
    </portType>
</definitions>