<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.zain.com/ZESB/Services/Applications/Common/Query/PaymentReceiptNumberQuery/PaymentReceiptNumberQueryResponse.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.zain.com/ZESB/Services/Applications/Common/Query/PaymentReceiptNumberQuery/PaymentReceiptNumberQueryRequest.xsd" xmlns:ns4="http://www.zain.com/ZESB/Services/PaymentReceiptNumberQuery/Fault.xsd" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.zain.com/BSS/ESB/Financial/PaymentReceiptNumberQuery" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns5="http://www.zain.com/ZESB/Services/PaymentReceiptNumberQueryRequest.xsd" xmlns:ns6="http://www.zain.com/ZESB/Services/PaymentReceiptNumberQueryResponse.xsd" targetNamespace="http://xmlns.zain.com/BSS/ESB/Financial/PaymentReceiptNumberQuery">
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <import namespace="http://www.zain.com/ZESB/Services/PaymentReceiptNumberQuery/Fault.xsd" location="../../../BusinessSchemas/Services/Applications/Common/Query/PaymentReceiptNumberQuery/Fault.xsd"/>
    <import namespace="http://www.zain.com/ZESB/Services/PaymentReceiptNumberQueryRequest.xsd" location="../../../BusinessSchemas/Services/Applications/Common/Query/PaymentReceiptNumberQuery/PaymentReceiptNumberQueryRequest.xsd"/>
    <import namespace="http://www.zain.com/ZESB/Services/PaymentReceiptNumberQueryResponse.xsd" location="../../../BusinessSchemas/Services/Applications/Common/Query/PaymentReceiptNumberQuery/PaymentReceiptNumberQueryResponse.xsd"/>
    <message name="PaymentReceiptNumberQueryInput">
        <part name="Input" element="ns5:PaymentReceiptNumberQueryRequest"/>
    </message>
    <message name="PaymentReceiptNumberQueryOutput">
        <part name="Output" element="ns6:PaymentReceiptNumberQueryResponse"/>
    </message>
    <message name="PaymentReceiptNumberQueryFault">
        <part name="Fault" element="ns4:fault"/>
    </message>
    <portType name="PaymentReceiptNumberQueryPort">
        <operation name="PaymentReceiptNumberQuery">
            <input message="tns:PaymentReceiptNumberQueryInput"/>
            <output message="tns:PaymentReceiptNumberQueryOutput"/>
            <fault name="fault1" message="tns:PaymentReceiptNumberQueryFault"/>
        </operation>
    </portType>
</definitions>