<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/PortInNumberUpdate.xsd" xmlns:tns="http://xmlns.example.com/1492438825142" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1492438825142">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/PortInNumberUpdate.xsd" location="../../../BusinessSchemas/Services/Modification/PortInNumberUpdate/PortInNumberUpdate.xsd"/>
    <message name="PortInNumberUpdateRequest">
        <part name="Input" element="ns:PortInNumberUpdateInput"/>
    </message>
    <message name="PortInNumberUpdateResponse">
        <part name="Output" element="ns:PortInNumberUpdateOutput"/>
    </message>
    <portType name="PortInNumberUpdatePort">
        <operation name="PortInNumberUpdate">
            <input message="tns:PortInNumberUpdateRequest"/>
            <output message="tns:PortInNumberUpdateResponse"/>
        </operation>
    </portType>
</definitions>