<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/PrepaidCDRQuery.xsd" xmlns:tns="http://xmlns.example.com/1494247679330" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1494247679330">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/PrepaidCDRQuery.xsd" location="../../../BusinessSchemas/Services/Query/PrepaidCDRQuery/PrepaidCDRQuery.xsd"/>
    <message name="PrepaidCDRQueryInput">
        <part name="Input" element="ns:PrepaidCDRQueryRequest"/>
    </message>
    <message name="PrepaidCDRQueryOutput">
        <part name="Output" element="ns:PrepaidCDRQueryResponse"/>
    </message>
    <portType name="PrepaidCDRQueryPort">
        <operation name="PrepaidCDRQuery">
            <input message="tns:PrepaidCDRQueryInput"/>
            <output message="tns:PrepaidCDRQueryOutput"/>
        </operation>
    </portType>
</definitions>