<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/OrderStatus.xsd" xmlns:ns="http://www.siebel.com/xml/CBiO2%20Order%20Provisioning%20Res%20IO" xmlns:ns4="http://www.zain.kw.com/BSS/OrderManagement/CreateOrderResponse" xmlns:ns3="http://www.zain.kw.com/BSS/OrderManagement/CreateOrderRequest" xmlns:tns="http://xmlns.example.com/1458646681478" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns5="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" targetNamespace="http://xmlns.example.com/1458646681478">
    <import namespace="http://www.siebel.com/xml/CBiO2%20Order%20Provisioning%20Res%20IO" location="../../../BusinessSchemas/Services/Applications/CRM/Provisioning/XSD/listOfCbio2LineItemResIo.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/OrderStatus.xsd" location="../../../BusinessSchemas/Services/Query/QueryOrderStatus/QueryOrderStatus.xsd"/>
    <import namespace="http://www.zain.kw.com/BSS/OrderManagement/CreateOrderRequest" location="../OM/OrderQuery.wsdl"/>
    <import namespace="http://www.zain.kw.com/BSS/OrderManagement/CreateOrderResponse" location="../../../BusinessSchemas/Services/Applications/ConceptWave/XSD/EOM.COM.orderResponse.xsd"/>
    <import namespace="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" location="../../../BusinessSchemas/Services/Common/SOAP/Fault.xsd"/>
    <message name="QueryOrderStatusInput">
        <part name="QueryOrderStatusInput" element="ns2:QueryOrderStatusInput"/>
    </message>
    <message name="QueryOrderStatusOutput">
        <part name="QueryOrderStatusOutput" element="ns4:orderResponse"/>
    </message>
    <message name="FaultMessage">
        <part name="Fault" element="ns5:ExceptionRequest"/>
    </message>
    <portType name="QueryOrderStatusPortType">
        <operation name="QueryOrderStatus">
            <input message="tns:QueryOrderStatusInput"/>
            <output message="tns:QueryOrderStatusOutput"/>
            <fault name="fault" message="tns:FaultMessage"/>
        </operation>
    </portType>
</definitions>