<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/QueryChakScreen.xsd" xmlns:tns="http://xmlns.example.com/1500231957757" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1500231957757">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/QueryChakScreen.xsd" location="../../../BusinessSchemas/Services/Query/QueryChakScreen/QueryChakScreen.xsd"/>
    <message name="QueryChakScreenRequest">
        <part name="Input" element="ns:QueryChakScreenInput"/>
    </message>
    <message name="QueryChakScreenResponse">
        <part name="Output" element="ns:QueryChakScreenOutput"/>
    </message>
    <portType name="QueryChakScreenPort">
        <operation name="QueryChakScreen">
            <input message="tns:QueryChakScreenRequest"/>
            <output message="tns:QueryChakScreenResponse"/>
        </operation>
    </portType>
</definitions>