<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.zain.com/BusinessSchemas/Services/Query/QueryServiceOrder/QueryServiceOrderRes.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.zain.com/BusinessSchemas/Services/Query/QueryServiceOrder/QueryServiceOrderReq.xsd" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.example.com/1464088852698" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1464088852698">
    <import namespace="http://www.zain.com/BusinessSchemas/Services/Query/QueryServiceOrder/QueryServiceOrderReq.xsd" location="../../../BusinessSchemas/Services/Query/QueryServiceOrder/QueryServiceOrderReq.xsd"/>
    <import namespace="http://www.zain.com/BusinessSchemas/Services/Query/QueryServiceOrder/QueryServiceOrderRes.xsd" location="../../../BusinessSchemas/Services/Query/QueryServiceOrder/QueryServiceOrderRes.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <message name="QueryServiceOrderReq">
        <part name="In" element="ns:QueryServiceOrderReq"/>
    </message>
    <message name="QueryServiceOrderRes">
        <part name="Op" element="ns2:QueryServiceOrderRes"/>
    </message>
    <message name="QueryServiceOrderFault">
        <part name="Fault" element="ns3:ErrorResponse"/>
    </message>
    <portType name="QueryServiceOrderPortType">
        <operation name="QueryServiceOrderOperation">
            <input message="tns:QueryServiceOrderReq"/>
            <output message="tns:QueryServiceOrderRes"/>
            <fault name="fault1" message="tns:QueryServiceOrderFault"/>
        </operation>
    </portType>
</definitions>