<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.zain.com/ZESB/Services/Query/QueryBestPackage.xsd" xmlns:tns="http://www.zain.com/ZESB/Services/Query/QueryBestPackage" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zain.com/ZESB/Services/Query/QueryBestPackage">
    <import namespace="http://www.zain.com/ZESB/Services/Query/QueryBestPackage.xsd" location="../../../BusinessSchemas/Services/Query/QueryBestPackage/QueryBestPackage.xsd"/>
    <message name="QueryBestPackageRequest">
        <part name="Input" element="ns:QueryBestPackageInput"/>
    </message>
    <message name="QueryBestPackageResponse">
        <part name="Output" element="ns:QueryBestPackageOutput"/>
    </message>
    <message name="QueryBestPackageFault">
        <part name="Fault" element="ns:Fault"/>
    </message>
    <portType name="QueryBestPackagePort">
        <operation name="QueryBestPackageOperation">
            <input message="tns:QueryBestPackageRequest"/>
            <output message="tns:QueryBestPackageResponse"/>
            <fault name="fault1" message="tns:QueryBestPackageFault"/>
        </operation>
    </portType>
</definitions>