<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/QueryReceiptNoCRM.xsd" xmlns:tns="http://xmlns.example.com/1499333771404" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1499333771404">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/QueryReceiptNoCRM.xsd" location="../../../BusinessSchemas/Services/Query/QueryReceiptNoCRM/QueryReceiptNoCRM.xsd"/>
    <message name="QueryReceiptNoCRMInput">
        <part name="Input" element="ns:QueryReceiptNoCRMRequest"/>
    </message>
    <message name="QueryReceiptNoCRMOutput">
        <part name="Output" element="ns:QueryReceiptNoCRMResponse"/>
    </message>
    <portType name="QueryReceiptNoCRMPort">
        <operation name="QueryReceiptNoCRM">
            <input message="tns:QueryReceiptNoCRMInput"/>
            <output message="tns:QueryReceiptNoCRMOutput"/>
        </operation>
    </portType>
</definitions>