<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/QueryContractStatementReport.xsd" xmlns:tns="http://xmlns.example.com/1515589891836" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1515589891836">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/QueryContractStatementReport.xsd" location="../../../BusinessSchemas/Services/Query/QueryContractStatementReport/QueryContractStatementReport.xsd"/>
    <message name="QueryContractStatementReportRequest">
        <part name="Input" element="ns:QueryContractStatementReportInput"/>
    </message>
    <message name="QueryContractStatementReportResponse">
        <part name="Output" element="ns:QueryContractStatementReportOutput"/>
    </message>
    <portType name="QueryContractStatementReportPort">
        <operation name="QueryContractStatementReportOperation">
            <input message="tns:QueryContractStatementReportRequest"/>
            <output message="tns:QueryContractStatementReportResponse"/>
        </operation>
    </portType>
</definitions>