<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Query/RoamingCDRQueryRes.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Query/RoamingCDRQueryReq.xsd" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.example.com/1487670243323" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1487670243323">
    <import namespace="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Query/RoamingCDRQueryReq.xsd" location="../../../BusinessSchemas/Services/Query/RoamingCDRQuery/RoamingCDRReq.xsd"/>
    <import namespace="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Query/RoamingCDRQueryRes.xsd" location="../../../BusinessSchemas/Services/Query/RoamingCDRQuery/RoamingCDRRes.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <message name="Request">
        <part name="part1" element="ns:CDRRequest"/>
    </message>
    <message name="Response">
        <part name="part1" element="ns2:RoamingCDRRes"/>
    </message>
    <message name="Fault">
        <part name="part1" element="ns3:ErrorResponse"/>
    </message>
    <portType name="RoamingCDRQueryPortType">
        <operation name="RoamingCDRQuery">
            <input message="tns:Request"/>
            <output message="tns:Response"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>