<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/RoamIntlDisconnect.xsd" xmlns:tns="http://xmlns.example.com/1499167907086" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1499167907086">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Modification/RoamIntlDisconnect.xsd" location="../../../BusinessSchemas/Services/Modification/RoamIntlDisconnect/RoamIntlDisconnect.xsd"/>
    <message name="RoamIntlDisconnectInput">
        <part name="Input" element="ns:RoamIntlDisconnectRequest"/>
    </message>
    <message name="RoamIntlDisconnectOutput">
        <part name="Output" element="ns:RoamIntlDisconnectResponse"/>
    </message>
    <portType name="RoamIntlDisconnectPort">
        <operation name="RoamIntlDisconnect">
            <input message="tns:RoamIntlDisconnectInput"/>
            <output message="tns:RoamIntlDisconnectOutput"/>
        </operation>
    </portType>
</definitions>