<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://xmlns.zain.com/BSS/ESB/CDM/SMSQuery" xmlns:tns="http://xmlns.example.com/1457447929024" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1457447929024">
    <import namespace="http://xmlns.zain.com/BSS/ESB/CDM/SMSQuery" location="../../../BusinessSchemas/Services/Notification/SMSQuery/SMSQuery.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../CDM/ZainKWFault.xsd"/>
    <message name="SMSQueryRequest">
        <part name="Input" element="ns:SMSQueryRequest"/>
    </message>
    <message name="SMSQueryResponse">
        <part name="Output" element="ns:SMSQueryResponse"/>
    </message>
    <message name="SMSQueryFault">
        <part name="Fault" element="ns2:ErrorResponse"/>
    </message>
    <portType name="SMSQuery">
        <operation name="SMSQuery">
            <input message="tns:SMSQueryRequest"/>
            <output message="tns:SMSQueryResponse"/>
            <fault name="fault1" message="tns:SMSQueryFault"/>
        </operation>
    </portType>
</definitions>