<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/StorageMediumDetailsRead.xsd" xmlns:tns="http://xmlns.example.com/1462960355565" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1462960355565">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/StorageMediumDetailsRead.xsd" location="../../../BusinessSchemas/Services/Query/StorageMediumDetailsRead/StorageMediumDetailsRead.xsd"/>
    <message name="StorageMediumDetailsReadRequest">
        <part name="Input" element="ns:StorageMediumDetailsReadInput"/>
    </message>
    <message name="StorageMediumDetailsReadResponse">
        <part name="Output" element="ns:StorageMediumDetailsReadOutput"/>
    </message>
    <message name="FaultMessage">
        <part name="Fault" element="ns:Fault"/>
    </message>
    <portType name="StorageMediumDetailsReadPort">
        <operation name="StorageMediumDetailsReadOperation">
            <input message="tns:StorageMediumDetailsReadRequest"/>
            <output message="tns:StorageMediumDetailsReadResponse"/>
            <fault name="fault1" message="tns:FaultMessage"/>
        </operation>
    </portType>
</definitions>