<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Applications/Common/SubscriberBPAssignment/Schema.xsd2" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Applications/Common/SubscriberBPAssignment/Schema.xsd" xmlns:ns3="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/Fault.xsd" xmlns:tns="http://xmlns.example.com/1473069987528" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1473069987528">
    <import namespace="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Applications/Common/SubscriberBPAssignment/Schema.xsd" location="../../../BusinessSchemas/Services/Applications/Common/SubscriberBPAssignment/SubscriberBPAssignmentInput.xsd"/>
    <import namespace="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Applications/Common/SubscriberBPAssignment/Schema.xsd2" location="../../../BusinessSchemas/Services/Applications/Common/SubscriberBPAssignment/SubscriberBPAssignmentOutput.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/Fault.xsd" location="../../../BusinessSchemas/Services/Applications/Common/SubscriberBPAssignment/Fault.xsd"/>
    <message name="SubscriberBPAssignmentReq">
        <part name="request" element="ns:SubscriberBPAssignmentRequest"/>
    </message>
    <message name="SubscriberBPAssignmentRes">
        <part name="response" element="ns2:SubscriberBPAssignmentResponse"/>
    </message>
    <message name="Fault">
        <part name="fault" element="ns3:ExceptionRequest"/>
    </message>
    <portType name="BPAssignment">
        <operation name="BPAssignment">
            <input message="tns:SubscriberBPAssignmentReq"/>
            <output message="tns:SubscriberBPAssignmentRes"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>