<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/ConceptWave/TerminateInstallment/TerminateInstallment.xsd" xmlns:tns="http://xmlns.example.com/1482160120243" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1482160120243">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/ConceptWave/TerminateInstallment/TerminateInstallment.xsd" location="../../../BusinessSchemas/Services/Applications/ConceptWave/TerminateInstallment/TerminateInstallment.xsd"/>
    <message name="TerminateInstallmentInput">
        <part name="Input" element="ns:TerminateInstallmentRequest"/>
    </message>
    <message name="TerminateInstallmentOutput">
        <part name="Output" element="ns:TerminateInstallmentResponse"/>
    </message>
    <portType name="TerminateInstallmentPort">
        <operation name="TerminateInstallment">
            <input message="tns:TerminateInstallmentInput"/>
            <output message="tns:TerminateInstallmentOutput"/>
        </operation>
    </portType>
</definitions>