<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.ericsson.com/ZainKW/BusinessSchemas/UpdateDABalanceAndDateRes.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/UpdateDABalanceAndDateReq.xsd" xmlns:tns="http://xmlns.zain.com/BSS/ESB/Financial/UpdateDABalanceAndDate" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.zain.com/BSS/ESB/Financial/UpdateDABalanceAndDate">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/UpdateDABalanceAndDateReq.xsd" location="../../../BusinessSchemas/Services/Transaction/UpdateDABalanceAndDate/UpdateDABalanceAndDateReq.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/UpdateDABalanceAndDateRes.xsd" location="../../../BusinessSchemas/Services/Transaction/UpdateDABalanceAndDate/UpdateDABalanceAndDateRes.xsd"/>
    <message name="UpdateDABalanceAndDateReq">
        <part name="Req" element="ns:UpdateDABalanceAndDateReq"/>
    </message>
    <message name="UpdateDABalanceAndDateRes">
        <part name="Res" element="ns2:UpdateDABalanceAndDateRes"/>
    </message>
    <portType name="UpdateDABalanceAndDatePortType">
        <operation name="UpdateDABalanceAndDateOp">
            <input message="tns:UpdateDABalanceAndDateReq"/>
            <output message="tns:UpdateDABalanceAndDateRes"/>
        </operation>
    </portType>
</definitions>