<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.tibco.com/schemas/CommonProject/BusinessWSDLS/Services/IVR/IVRPinResetResponse.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/CommonProject/BusinessWSDLS/Services/IVR/IVRPinResetRequest.xsd" xmlns:ns3="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" xmlns:tns="http://www.zain.com/ZESB/Services/IVRPinReset" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zain.com/ZESB/Services/IVRPinReset">
    <import location="IVRPinResetRequest.xsd" namespace="http://www.tibco.com/schemas/CommonProject/BusinessWSDLS/Services/IVR/IVRPinResetRequest.xsd"/>
    <import location="IVRPinResetResponse.xsd" namespace="http://www.tibco.com/schemas/CommonProject/BusinessWSDLS/Services/IVR/IVRPinResetResponse.xsd"/>
    <import location="../../../BusinessSchemas/Services/Common/SOAP/Fault.xsd" namespace="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd"/>
    <message name="IVRPinResetRequest">
        <part element="ns:IVRPinResetRequest" name="Request"/>
    </message>
    <message name="IVRPinResetResponse">
        <part element="ns2:IVRPinResetResponse" name="Response"/>
    </message>
    <message name="fault">
        <part element="ns3:ExceptionRequest" name="fault"/>
    </message>
    <portType name="IVRPinReset">
        <operation name="IVRPinReset">
            <input message="tns:IVRPinResetRequest"/>
            <output message="tns:IVRPinResetResponse"/>
            <fault message="tns:fault" name="fault1"/>
        </operation>
    </portType>
</definitions>