<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.ericsson.com/ZainKW/CommonProject/BusinessSchemas/Services/Query/GetChargeHistory/GetChargeHistoryRes.xsd" xmlns:ns="http://www.ericsson.com/ZainKW/CommonProject/BusinessSchemas/Services/Query/GetChargeHistory/GetChargeHistoryReq.xsd" xmlns:ns3="http://www.zain.com/ZESB/Types/Common" xmlns:tns="http://xmlns.example.com/1400234971903" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1400234971903">
    <import namespace="http://www.ericsson.com/ZainKW/CommonProject/BusinessSchemas/Services/Query/GetChargeHistory/GetChargeHistoryReq.xsd" location="../../../../../BusinessSchemas/Services/Query/GetChargeHistory/GetChargeHistoryReq.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/CommonProject/BusinessSchemas/Services/Query/GetChargeHistory/GetChargeHistoryRes.xsd" location="../../../../../BusinessSchemas/Services/Query/GetChargeHistory/GetChargeHistoryRes.xsd"/>
    <import namespace="http://www.zain.com/ZESB/Types/Common" location="../../../../../BusinessWSDLS/Services/Generic/Fault/Fault.xsd"/>
    <message name="InputMessage">
        <part name="part1" element="ns:GetChargeHistoryReq"/>
    </message>
    <message name="OutputMessage">
        <part name="part1" element="ns2:GetChargeHistoryRes"/>
    </message>
    <message name="Fault">
        <part name="part1" element="ns3:FaultType"/>
    </message>
    <portType name="GetChargeHistoryPortType">
        <operation name="GetChargeHistoryOperation">
            <input message="tns:InputMessage"/>
            <output message="tns:OutputMessage"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>