<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="urn:siemens:names:prov:gw:SUBSCRIBER:1:0:wsdl" xmlns:intf="urn:siemens:names:prov:gw:SUBSCRIBER:1:0:wsdl" xmlns:tns1="http://soapadapter.provgw" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:siemens:names:prov:gw:SUBSCRIBER:1:0:wsdl">
    <wsdl:types>
        <schema targetNamespace="http://soapadapter.provgw" xmlns="http://www.w3.org/2001/XMLSchema">
            <element name="receiveRequest" type="xsd:anyType"/>
        </schema>
        <schema targetNamespace="urn:siemens:names:prov:gw:SUBSCRIBER:1:0:wsdl" xmlns="http://www.w3.org/2001/XMLSchema">
            <element name="receiveRequestReturn" type="xsd:anyType"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="receiveRequestResponse">
        <wsdl:part name="receiveRequestReturn" element="impl:receiveRequestReturn"/>
    </wsdl:message>
    <wsdl:message name="receiveRequestRequest">
        <wsdl:part name="part" element="tns1:receiveRequest"/>
    </wsdl:message>
    <wsdl:portType name="SPMLSubscriber10PortType">
        <wsdl:operation name="receiveRequest">
            <wsdl:input name="receiveRequestRequest" message="impl:receiveRequestRequest"/>
            <wsdl:output name="receiveRequestResponse" message="impl:receiveRequestResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="SPMLSubscriber10SoapBinding" type="impl:SPMLSubscriber10PortType">
        <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="receiveRequest">
            <wsdlsoap:operation soapAction=""/>
            <wsdl:input name="receiveRequestRequest">
                <wsdlsoap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="receiveRequestResponse">
                <wsdlsoap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="SPMLSubscriber10">
        <wsdl:port name="SPMLSubscriber10" binding="impl:SPMLSubscriber10SoapBinding">
            <wsdlsoap:address location="http://10.24.98.21:8081/ProvisioningGateway/services/SPMLSubscriber10Service"/>
        </wsdl:port>
    </wsdl:service>
    <!--WSDL created by Apache Axis version: 1.3
Built on Jul 21, 2006 (10:49:20 CEST)-->
</wsdl:definitions>
