<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.zain.kw.com/BSS/OrderManagement/Inventory/queryManualTaskList" xmlns:ns4="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/GWOrd_queryManualTaskList_Res.xsd" xmlns:ns="http://www.zain.kw.com/BSS/OrderManagement/Inventory/GWOrdMgmt_QueryManualTask" xmlns:ns3="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/GWOrd_queryManualTaskList_Req.xsd" xmlns:tns="http://www.zain.kw.com/BSS/OrderManagement/Inventory/queryManualTaskList" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zain.kw.com/BSS/OrderManagement/Inventory/GWOrdMgmt_QueryManualTask">
    <import namespace="http://www.zain.kw.com/BSS/OrderManagement/Inventory/queryManualTaskList" location="queryManualTaskList.wsdl"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/GWOrd_queryManualTaskList_Req.xsd" location="GWOrd_queryManualTaskList_Req.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/GWOrd_queryManualTaskList_Res.xsd" location="GWOrd_queryManualTaskList_Res.xsd"/>
    <message name="QueryManualTaskRequest">
        <part name="queryManualtaskRequest" element="ns3:queryManualTaskListRequest"/>
    </message>
    <message name="QueryManualTaskResponse">
        <part name="queryManualTaskResponse" element="ns4:queryManualTaskListResponse"/>
    </message>
    <portType name="QueryManualTaskPort">
        <operation name="QueryManualTaskOp">
            <input message="ns:QueryManualTaskRequest"/>
            <output message="ns:QueryManualTaskResponse"/>
        </operation>
    </portType>
</definitions>