<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/UnBar_getSubInfo/UnBar_getSubInfoResponse.xsd" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/UnBar_getSubInfo/UnBar_getSubInfo.xsd" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.zain.com/BSS/ESB/getSubInfo" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.zain.com/BSS/ESB/getSubInfo">
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../../CDM/ZainKWFault.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/UnBar_getSubInfo/UnBar_getSubInfo.xsd" location="../../../../BusinessSchemas/Services/UnBar_getSubInfo/UnBar_getSubInfo.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/UnBar_getSubInfo/UnBar_getSubInfoResponse.xsd" location="../../../../BusinessSchemas/Services/UnBar_getSubInfo/UnBar_getSubInfoResponse.xsd"/>
    <message name="getSubInfo_Input">
        <part name="getSubInfo_In" element="ns:getSubInfo"/>
    </message>
    <message name="getSubInfo_Output">
        <part name="getSubInfo_Out" element="ns2:subscriberInfo"/>
    </message>
    <message name="getSubInfo_fault">
        <part element="ns3:ErrorResponse" name="fault"/>
    </message>
    <portType name="getSubInfo">
        <operation name="getSubInfo">
            <input message="tns:getSubInfo_Input"/>
            <output message="tns:getSubInfo_Output"/>
            <fault message="tns:getSubInfo_fault" name="fault1"/>
        </operation>
    </portType>
</definitions>