<?xml version="1.0" encoding="UTF-8"?><definitions
 xmlns="http://schemas.xmlsoap.org/wsdl/"
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
 targetNamespace="http://siebel.com/CustomUI"
 xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:tns="http://siebel.com/CustomUI"
><types
></types
><message
 name="CancelOrder_Input"
><part
 name="BasicServiceType"
 type="xsd:string"
></part
><part
 name="Requester"
 type="xsd:string"
></part
><part
 name="UserName"
 type="xsd:string"
></part
><part
 name="MSISDN"
 type="xsd:string"
></part
><part
 name="OrderType"
 type="xsd:string"
></part
><part
 name="LineType"
 type="xsd:string"
></part
><part
 name="CancelReason"
 type="xsd:string"
></part
><part
 name="Charged"
 type="xsd:string"
></part
><part
 name="TransactionId"
 type="xsd:string"
></part
></message
><message
 name="CancelOrder_Output"
><part
 name="Error_spcCode"
 type="xsd:string"
></part
><part
 name="Error_spcMessage"
 type="xsd:string"
></part
><part
 name="OrderNumber"
 type="xsd:string"
></part
></message
><portType
 name="CancelFutureOrder"
><operation
 name="CancelOrder"
><input
 message="tns:CancelOrder_Input"
></input
><output
 message="tns:CancelOrder_Output"
></output
></operation
></portType
><binding
 name="CancelFutureOrder"
 type="tns:CancelFutureOrder"
><soap:binding
 transport="http://schemas.xmlsoap.org/soap/http"
 style="rpc"
></soap:binding
><operation
 name="CancelOrder"
><soap:operation
 soapAction="rpc/http://siebel.com/CustomUI:CancelOrder"
></soap:operation
><input
><soap:body
 namespace="http://siebel.com/CustomUI"
 use="literal"
></soap:body
></input
><output
><soap:body
 namespace="http://siebel.com/CustomUI"
 use="literal"
></soap:body
></output
></operation
></binding
><service
 name="CBiO2CancelFutureDatedOrder"
><port
 binding="tns:CancelFutureOrder"
 name="CancelFutureOrder"
><soap:address
 location="http://10.103.23.115:7777/eai_anon_enu/start.swe?SWEExtCmd=Execute&amp;SWEExtSource=SecureWebService&amp;WSSOAP=1"
></soap:address
></port
></service
></definitions
>