<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://siebel.com/CustomUI" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://siebel.com/CustomUI">
    <types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" targetNamespace="http://siebel.com/CustomUI">
            <xsd:element name="CheckCRMStatus_Input">
                <xsd:complexType>
                    <xsd:sequence/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="CheckCRMStatus_Output">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="Status" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:schema>
    </types>
    <message name="CheckCRMStatus_Input">
        <part name="CheckCRMStatus_Input" element="tns:CheckCRMStatus_Input"/>
    </message>
    <message name="CheckCRMStatus_Output">
        <part name="CheckCRMStatus_Output" element="tns:CheckCRMStatus_Output"/>
    </message>
    <portType name="CheckCRMStatus">
        <operation name="CheckCRMStatus">
            <input message="tns:CheckCRMStatus_Input"/>
            <output message="tns:CheckCRMStatus_Output"/>
        </operation>
    </portType>
    <binding name="CheckCRMStatus" type="tns:CheckCRMStatus">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="CheckCRMStatus">
            <soap:operation soapAction="document/http://siebel.com/CustomUI:CheckCRMStatus"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="CBiO2_spcCheck_spcCRM_spcStatus_spcFlow">
        <port binding="tns:CheckCRMStatus" name="CheckCRMStatus">
            <soap:address location="http://10.103.23.115:7777/eai_anon_enu/start.swe?SWEExtCmd=Execute&amp;SWEExtSource=SecureWebService&amp;WSSOAP=1"/>
        </port>
    </service>
</definitions>