<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/CRM/Query/GetPrepaidBalanceResponse.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/CRM/Query/GetPrepaidBalanceRequest.xsd" xmlns:ns3="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" xmlns:tns="http://xmlns.example.com/1443171607902" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1443171607902">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/CRM/Query/GetPrepaidBalanceRequest.xsd" location="../../../BusinessSchemas/Services/Applications/CRM/Query/GetPrepaidBalance/GetPrepaidBalanceRequest.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/CRM/Query/GetPrepaidBalanceResponse.xsd" location="../../../BusinessSchemas/Services/Applications/CRM/Query/GetPrepaidBalance/GetPrepaidBalanceResponse.xsd"/>
    <import namespace="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" location="../../../BusinessSchemas/Services/Common/SOAP/Fault.xsd"/>
    <message name="GetPrepaidBalanceRequest">
        <part name="GetPrepaidBalanceRequest" element="ns:GetPrepaidBalanceRequest"/>
    </message>
    <message name="GetPrepaidBalanceResponse">
        <part name="GetPrepaidBalanceResponse" element="ns2:GetPrepaidBalanceResponse"/>
    </message>
    <message name="Fault">
        <part name="Fault" element="ns3:ExceptionRequest"/>
    </message>
    <portType name="GetPrepaidBalancePortType">
        <operation name="GetPrepaidBalanceOperation">
            <input message="tns:GetPrepaidBalanceRequest"/>
            <output message="tns:GetPrepaidBalanceResponse"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>