<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions name="SMSService" targetNamespace="http://example.org" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://example.org" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
<xs:schema elementFormDefault="unqualified" targetNamespace="http://example.org" version="1.0" xmlns:tns="http://example.org" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="SMSDetails" type="tns:SMSDetails"/>
<xs:element name="SMSDetailsResponse" type="tns:SMSDetailsResponse"/>
<xs:complexType name="SMSDetails">
    <xs:sequence>
      <xs:element name="SOURCE_ADDR" type="xs:string"/>
      <xs:element minOccurs="0" name="CONTRACT_ID" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
<xs:complexType name="SMSDetailsResponse">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="SMSDetails" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="SMSDetailsResponse">
    <wsdl:part element="tns:SMSDetailsResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="SMSDetails">
    <wsdl:part element="tns:SMSDetails" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="SMSDetailsPortType">
    <wsdl:operation name="SMSDetails">
      <wsdl:input message="tns:SMSDetails" name="SMSDetails">
    </wsdl:input>
      <wsdl:output message="tns:SMSDetailsResponse" name="SMSDetailsResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SMSDetailsSoapBinding" type="tns:SMSDetailsPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="SMSDetails">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="SMSDetails">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="SMSDetailsResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SMSDetailsService">
    <wsdl:port binding="tns:SMSDetailsSoapBinding" name="SMSDetailsPortTypePort">
      <soap:address location="http://localhost:8081/SMS_GATEWAY/SMSDetails.yaws"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
