<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.tibco.com/schemas/GW/BusinessProcesses/Services/CRM/Query/OutstandingQuery/Implementation/OutstandingQueryOutput.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/GW/BusinessProcesses/Services/CRM/Query/OutstandingQuery/Implementation/OutstandingQueryInput.xsd" xmlns:ns4="http://xmlns.zain.com/BSS/ESB/Fault.xsd" xmlns:ns3="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" xmlns:tns="http://xmlns.example.com/1450705839867" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns5="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" targetNamespace="http://xmlns.example.com/1450705839867">
    <import namespace="http://xmlns.zain.com/BSS/ESB/Fault.xsd" location="../../../../../../BusinessSchemas/Services/Common/SOAP/Fault.xsd"/>
    <import namespace="http://www.tibco.com/schemas/GW/BusinessProcesses/Services/CRM/Query/OutstandingQuery/Implementation/OutstandingQueryInput.xsd" location="../../../../../../BusinessSchemas/Services/Applications/Common/Query/OutstandingQuery/OutstandingQueryInput.xsd"/>
    <import namespace="http://www.tibco.com/schemas/GW/BusinessProcesses/Services/CRM/Query/OutstandingQuery/Implementation/OutstandingQueryOutput.xsd" location="../../../../../../BusinessSchemas/Services/Applications/Common/Query/OutstandingQuery/OutstandingQueryOutput.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../../../../CDM/ZainKWFault.xsd"/>
    <message name="InputMessage">
        <part name="Input" element="ns:OutstandingQueryRequest"/>
    </message>
    <message name="OutputMessage">
        <part name="Output" element="ns2:OutstandingQueryResponse"/>
    </message>
    <message name="Fault">
        <part name="FaultMsg" element="ns5:ErrorResponse"/>
    </message>
    <portType name="OutstandingQuery">
        <operation name="OutstandingQuery">
            <input message="tns:InputMessage"/>
            <output message="tns:OutputMessage"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>