<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns4="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/OrderValidationInput.xsd" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/Fault.xsd" xmlns:ns3="http://www.zain.com/ZESB/Types/Common" xmlns:tns="http://www.zain.com/ZESB/Services/OrderValidation" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns5="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/OrderValidationOutput.xsd" xmlns:ns7="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" targetNamespace="http://www.zain.com/ZESB/Services/OrderValidation">
    <import namespace="http://www.ericsson.com/Mozaic/BusinessSchemas/SOAP/XSDs/Fault.xsd" location="../../../../BusinessSchemas/Services/Common/SOAP/Fault.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/OrderValidationInput.xsd" location="../../../../BusinessSchemas/Services/Applications/Common/OrderValidation/OrderValidationInput.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/OrderValidationOutput.xsd" location="../../../../BusinessSchemas/Services/Applications/Common/OrderValidation/OrderValidationOutput.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Applications/Common/Fault.xsd" location="../../../../BusinessSchemas/Services/Applications/Common/OrderValidation/Fault.xsd"/>
    <message name="OrderValidationInput">
        <part name="Input" element="ns4:OrderValidationRequest"/>
    </message>
    <message name="OrderValidationOutput">
        <part name="Output" element="ns5:OrderValidationResponse"/>
    </message>
    <message name="Fault">
        <part name="Fault" element="ns:ExceptionRequest"/>
    </message>
    <portType name="OrderValidationPortType">
        <operation name="OrderValidation">
            <input message="tns:OrderValidationInput"/>
            <output message="tns:OrderValidationOutput"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>