<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.tibco.com/schemas/GW_CustMgmt/BusinessProcesses/Services/CRM/Provisioning/FirstCallActivation/Implementation/Schema.xsd2" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/GW_CustMgmt/BusinessProcesses/Services/CRM/Provisioning/FirstCallActivation/Implementation/Schema.xsd" xmlns:tns="http://xmlns.example.com/1513973733001" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1513973733001">
    <import namespace="http://www.tibco.com/schemas/GW_CustMgmt/BusinessProcesses/Services/CRM/Provisioning/FirstCallActivation/Implementation/Schema.xsd" location="InputRequest.xsd"/>
    <import namespace="http://www.tibco.com/schemas/GW_CustMgmt/BusinessProcesses/Services/CRM/Provisioning/FirstCallActivation/Implementation/Schema.xsd2" location="OutputResponse.xsd"/>
    <message name="MessageIn">
        <part name="part1" element="ns:Input"/>
    </message>
    <message name="MessageOut">
        <part name="part1" element="ns2:Response"/>
    </message>
    <portType name="PortType">
        <operation name="FirstCall">
            <input message="tns:MessageIn"/>
            <output message="tns:MessageOut"/>
        </operation>
    </portType>
</definitions>