<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/QueryManualTask/GWOrd_queryManualTaskList_Res.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/QueryManualTask/GWOrd_queryManualTaskList_Req.xsd" xmlns:tns="http://www.zain.com/ZESB/Services/QueryManualTask" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.zain.com/ZESB/Services/QueryManualTask">
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/QueryManualTask/GWOrd_queryManualTaskList_Req.xsd" location="../../../../BusinessSchemas/Services/Query/QueryManualTask/GWOrd_queryManualTaskList_Req.xsd"/>
    <import namespace="http://www.ericsson.com/ZainKW/BusinessSchemas/Services/Query/QueryManualTask/GWOrd_queryManualTaskList_Res.xsd" location="../../../../BusinessSchemas/Services/Query/QueryManualTask/GWOrd_queryManualTaskList_Res.xsd"/>
    <message name="QueryManualTaskRequest">
        <part name="queryManualtaskRequest" element="ns:queryManualTaskListRequest"/>
    </message>
    <message name="QueryManualTaskResponse">
        <part name="queryManualTaskResponse" element="ns2:queryManualTaskListResponse"/>
    </message>
    <message name="FaultType">
        <part name="Fault" element="ns2:error"/>
    </message>
    <portType name="QueryManualTaskPort">
        <operation name="QueryManualTaskOp">
            <input message="tns:QueryManualTaskRequest"/>
            <output message="tns:QueryManualTaskResponse"/>
            <fault name="fault1" message="tns:FaultType"/>
        </operation>
    </portType>
</definitions>