<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Applications/Common/Query/InvoiceQuery/Schema.xsd" xmlns:ns="http://www.tibco.com/schemas/GW/BusinessProcesses/Services/CRM/Query/BillQueryPostpaid/Implementation/Schema.xsd" xmlns:ns3="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" xmlns:tns="http://xmlns.example.com/1480787441831" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1480787441831">
    <import namespace="http://www.tibco.com/schemas/GW/BusinessProcesses/Services/CRM/Query/BillQueryPostpaid/Implementation/Schema.xsd" location="../../../../../../BusinessSchemas/Services/Applications/Common/Query/InvoiceQuery/BillQueryInput.xsd"/>
    <import namespace="http://www.xmlns.zain.com/BSS/ESB/ZainKWFault.xsd" location="../../../../../../CDM/ZainKWFault.xsd"/>
    <import namespace="http://www.tibco.com/schemas/CommonProject/BusinessSchemas/Services/Applications/Common/Query/InvoiceQuery/Schema.xsd" location="../../../../../../BusinessSchemas/Services/Applications/Common/Query/InvoiceQuery/BillDetailsQueryCDM.xsd"/>
    <message name="InvoiceDetailQueryInput">
        <part name="InvoiceDetailQueryRequest" element="ns:BillQueryRequest"/>
    </message>
    <message name="InvoiceDetailQueryOutput">
        <part name="InvoiceDetailQueryResponse" element="ns2:Records"/>
    </message>
    <message name="Fault">
        <part name="Fault" element="ns3:ErrorResponse"/>
    </message>
    <portType name="InvoiceDetailQuery">
        <operation name="InvoiceDetailQuery">
            <input message="tns:InvoiceDetailQueryInput"/>
            <output message="tns:InvoiceDetailQueryOutput"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>